name: Coffeer
description: A Big Little World
meta_description: "Coffeer's Footprint"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'coffeerme'

# Details for the RSS feed generator
url:            'http://dingxizheng.com'
author:         'Coffeer'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
